// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace NetVips.AutoGen
{
    [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointer(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
    public unsafe delegate int VipsCallbackFn(global::System.IntPtr a, global::System.IntPtr b);

    [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointer(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
    public unsafe delegate global::System.IntPtr VipsSListMap2Fn(global::System.IntPtr item, global::System.IntPtr a, global::System.IntPtr b);

    [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointer(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
    public unsafe delegate global::System.IntPtr VipsSListMap4Fn(global::System.IntPtr item, global::System.IntPtr a, global::System.IntPtr b, global::System.IntPtr c, global::System.IntPtr d);

    [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointer(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
    public unsafe delegate global::System.IntPtr VipsSListFold2Fn(global::System.IntPtr item, global::System.IntPtr a, global::System.IntPtr b, global::System.IntPtr c);

    public unsafe partial class basic
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_path_filename7")]
            internal static extern sbyte* VipsPathFilename7([MarshalAs(UnmanagedType.LPStr)] string path);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_path_mode7")]
            internal static extern sbyte* VipsPathMode7([MarshalAs(UnmanagedType.LPStr)] string path);
        }

        public static char* VipsPathFilename7(string path)
        {
            var __ret = __Internal.VipsPathFilename7(path);
            return (char*) __ret;
        }

        public static char* VipsPathMode7(string path)
        {
            var __ret = __Internal.VipsPathMode7(path);
            return (char*) __ret;
        }
    }
}
