// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace NetVips.AutoGen
{
    public unsafe partial class enumtypes
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_blend_mode_get_type")]
            internal static extern ulong VipsBlendModeGetType();

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_interpretation_get_type")]
            internal static extern ulong VipsInterpretationGetType();

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_band_format_get_type")]
            internal static extern ulong VipsBandFormatGetType();

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_operation_flags_get_type")]
            internal static extern ulong VipsOperationFlagsGetType();
        }

        public static ulong VipsBlendModeGetType()
        {
            var __ret = __Internal.VipsBlendModeGetType();
            return __ret;
        }

        public static ulong VipsInterpretationGetType()
        {
            var __ret = __Internal.VipsInterpretationGetType();
            return __ret;
        }

        public static ulong VipsBandFormatGetType()
        {
            var __ret = __Internal.VipsBandFormatGetType();
            return __ret;
        }

        public static ulong VipsOperationFlagsGetType()
        {
            var __ret = __Internal.VipsOperationFlagsGetType();
            return __ret;
        }
    }
}
