// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace NetVips.AutoGen
{
    public unsafe partial class error
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_error_buffer")]
            internal static extern global::System.IntPtr VipsErrorBuffer();

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_error_clear")]
            internal static extern void VipsErrorClear();
        }

        public static string VipsErrorBuffer()
        {
            var __ret = __Internal.VipsErrorBuffer();
            return Marshal.PtrToStringAnsi(__ret);
        }

        public static void VipsErrorClear()
        {
            __Internal.VipsErrorClear();
        }
    }
}
