// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace NetVips.AutoGen
{
    public unsafe partial class foreign
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_foreign_find_load")]
            internal static extern global::System.IntPtr VipsForeignFindLoad([MarshalAs(UnmanagedType.LPStr)] string filename);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_foreign_find_load_buffer")]
            internal static extern global::System.IntPtr VipsForeignFindLoadBuffer(global::System.IntPtr data, ulong size);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_foreign_find_save")]
            internal static extern global::System.IntPtr VipsForeignFindSave([MarshalAs(UnmanagedType.LPStr)] string filename);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_foreign_find_save_buffer")]
            internal static extern global::System.IntPtr VipsForeignFindSaveBuffer([MarshalAs(UnmanagedType.LPStr)] string suffix);
        }

        public static string VipsForeignFindLoad(string filename)
        {
            var __ret = __Internal.VipsForeignFindLoad(filename);
            return Marshal.PtrToStringAnsi(__ret);
        }

        public static string VipsForeignFindLoadBuffer(global::System.IntPtr data, ulong size)
        {
            var __ret = __Internal.VipsForeignFindLoadBuffer(data, size);
            return Marshal.PtrToStringAnsi(__ret);
        }

        public static string VipsForeignFindSave(string filename)
        {
            var __ret = __Internal.VipsForeignFindSave(filename);
            return Marshal.PtrToStringAnsi(__ret);
        }

        public static string VipsForeignFindSaveBuffer(string suffix)
        {
            var __ret = __Internal.VipsForeignFindSaveBuffer(suffix);
            return Marshal.PtrToStringAnsi(__ret);
        }
    }
}
