// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace NetVips.AutoGen
{
    public unsafe partial class genums
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("libgobject-2.0-0.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="g_value_set_enum")]
            internal static extern void GValueSetEnum(global::System.IntPtr value, int v_enum);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libgobject-2.0-0.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="g_value_get_enum")]
            internal static extern int GValueGetEnum(global::System.IntPtr value);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libgobject-2.0-0.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="g_value_set_flags")]
            internal static extern void GValueSetFlags(global::System.IntPtr value, uint v_flags);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libgobject-2.0-0.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="g_value_get_flags")]
            internal static extern uint GValueGetFlags(global::System.IntPtr value);
        }

        public static void GValueSetEnum(global::NetVips.AutoGen.GValue value, int v_enum)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            __Internal.GValueSetEnum(__arg0, v_enum);
        }

        public static int GValueGetEnum(global::NetVips.AutoGen.GValue value)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            var __ret = __Internal.GValueGetEnum(__arg0);
            return __ret;
        }

        public static void GValueSetFlags(global::NetVips.AutoGen.GValue value, uint v_flags)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            __Internal.GValueSetFlags(__arg0, v_flags);
        }

        public static uint GValueGetFlags(global::NetVips.AutoGen.GValue value)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            var __ret = __Internal.GValueGetFlags(__arg0);
            return __ret;
        }
    }
}
