// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace NetVips.AutoGen
{
    [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointer(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
    public unsafe delegate void GPrintFunc([MarshalAs(UnmanagedType.LPStr)] string @string);

    public unsafe partial class gmessages
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("libglib-2.0-0.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="g_log_remove_handler")]
            internal static extern void GLogRemoveHandler([MarshalAs(UnmanagedType.LPStr)] string log_domain, uint handler_id);
        }

        public static void GLogRemoveHandler(string log_domain, uint handler_id)
        {
            __Internal.GLogRemoveHandler(log_domain, handler_id);
        }
    }
}
