// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace NetVips.AutoGen
{
    public unsafe partial class gvaluetypes
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("libgobject-2.0-0.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="g_value_set_boolean")]
            internal static extern void GValueSetBoolean(global::System.IntPtr value, int v_boolean);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libgobject-2.0-0.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="g_value_get_boolean")]
            internal static extern int GValueGetBoolean(global::System.IntPtr value);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libgobject-2.0-0.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="g_value_set_int")]
            internal static extern void GValueSetInt(global::System.IntPtr value, int v_int);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libgobject-2.0-0.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="g_value_get_int")]
            internal static extern int GValueGetInt(global::System.IntPtr value);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libgobject-2.0-0.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="g_value_set_double")]
            internal static extern void GValueSetDouble(global::System.IntPtr value, double v_double);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libgobject-2.0-0.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="g_value_get_double")]
            internal static extern double GValueGetDouble(global::System.IntPtr value);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libgobject-2.0-0.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="g_value_set_string")]
            internal static extern void GValueSetString(global::System.IntPtr value, [MarshalAs(UnmanagedType.LPStr)] string v_string);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libgobject-2.0-0.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="g_value_get_string")]
            internal static extern global::System.IntPtr GValueGetString(global::System.IntPtr value);
        }

        public static void GValueSetBoolean(global::NetVips.AutoGen.GValue value, int v_boolean)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            __Internal.GValueSetBoolean(__arg0, v_boolean);
        }

        public static int GValueGetBoolean(global::NetVips.AutoGen.GValue value)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            var __ret = __Internal.GValueGetBoolean(__arg0);
            return __ret;
        }

        public static void GValueSetInt(global::NetVips.AutoGen.GValue value, int v_int)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            __Internal.GValueSetInt(__arg0, v_int);
        }

        public static int GValueGetInt(global::NetVips.AutoGen.GValue value)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            var __ret = __Internal.GValueGetInt(__arg0);
            return __ret;
        }

        public static void GValueSetDouble(global::NetVips.AutoGen.GValue value, double v_double)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            __Internal.GValueSetDouble(__arg0, v_double);
        }

        public static double GValueGetDouble(global::NetVips.AutoGen.GValue value)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            var __ret = __Internal.GValueGetDouble(__arg0);
            return __ret;
        }

        public static void GValueSetString(global::NetVips.AutoGen.GValue value, string v_string)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            __Internal.GValueSetString(__arg0, v_string);
        }

        public static string GValueGetString(global::NetVips.AutoGen.GValue value)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            var __ret = __Internal.GValueGetString(__arg0);
            return Marshal.PtrToStringAnsi(__ret);
        }
    }
}
