// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace NetVips.AutoGen
{
    [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointer(global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
    public unsafe delegate global::System.IntPtr VipsImageMapFn(global::System.IntPtr image, [MarshalAs(UnmanagedType.LPStr)] string name, global::System.IntPtr value, global::System.IntPtr a);

    public unsafe partial class header
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_image_set")]
            internal static extern void VipsImageSet(global::System.IntPtr image, [MarshalAs(UnmanagedType.LPStr)] string name, global::System.IntPtr value);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_image_get")]
            internal static extern int VipsImageGet(global::System.IntPtr image, [MarshalAs(UnmanagedType.LPStr)] string name, global::System.IntPtr value_copy);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_image_get_typeof")]
            internal static extern ulong VipsImageGetTypeof(global::System.IntPtr image, [MarshalAs(UnmanagedType.LPStr)] string name);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_image_remove")]
            internal static extern int VipsImageRemove(global::System.IntPtr image, [MarshalAs(UnmanagedType.LPStr)] string name);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_image_get_fields")]
            internal static extern sbyte** VipsImageGetFields(global::System.IntPtr image);
        }

        public static void VipsImageSet(global::NetVips.AutoGen.VipsImage image, string name, global::NetVips.AutoGen.GValue value)
        {
            var __arg0 = ReferenceEquals(image, null) ? global::System.IntPtr.Zero : image.__Instance;
            var __arg2 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            __Internal.VipsImageSet(__arg0, name, __arg2);
        }

        public static int VipsImageGet(global::NetVips.AutoGen.VipsImage image, string name, global::NetVips.AutoGen.GValue value_copy)
        {
            var __arg0 = ReferenceEquals(image, null) ? global::System.IntPtr.Zero : image.__Instance;
            var __arg2 = ReferenceEquals(value_copy, null) ? global::System.IntPtr.Zero : value_copy.__Instance;
            var __ret = __Internal.VipsImageGet(__arg0, name, __arg2);
            return __ret;
        }

        public static ulong VipsImageGetTypeof(global::NetVips.AutoGen.VipsImage image, string name)
        {
            var __arg0 = ReferenceEquals(image, null) ? global::System.IntPtr.Zero : image.__Instance;
            var __ret = __Internal.VipsImageGetTypeof(__arg0, name);
            return __ret;
        }

        public static int VipsImageRemove(global::NetVips.AutoGen.VipsImage image, string name)
        {
            var __arg0 = ReferenceEquals(image, null) ? global::System.IntPtr.Zero : image.__Instance;
            var __ret = __Internal.VipsImageRemove(__arg0, name);
            return __ret;
        }

        public static char** VipsImageGetFields(global::NetVips.AutoGen.VipsImage image)
        {
            var __arg0 = ReferenceEquals(image, null) ? global::System.IntPtr.Zero : image.__Instance;
            var __ret = __Internal.VipsImageGetFields(__arg0);
            return (char**) __ret;
        }
    }
}
