// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace NetVips.AutoGen
{
    public unsafe partial class type
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_value_get_ref_string")]
            internal static extern global::System.IntPtr VipsValueGetRefString(global::System.IntPtr value, ulong* length);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_value_set_ref_string")]
            internal static extern void VipsValueSetRefString(global::System.IntPtr value, [MarshalAs(UnmanagedType.LPStr)] string str);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_value_get_blob")]
            internal static extern global::System.IntPtr VipsValueGetBlob(global::System.IntPtr value, ulong* length);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_value_set_blob")]
            internal static extern void VipsValueSetBlob(global::System.IntPtr value, global::System.IntPtr free_fn, global::System.IntPtr data, ulong length);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_value_set_blob_free")]
            internal static extern void VipsValueSetBlobFree(global::System.IntPtr value, global::System.IntPtr data, ulong length);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_value_get_array_double")]
            internal static extern double* VipsValueGetArrayDouble(global::System.IntPtr value, int* n);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_value_set_array_double")]
            internal static extern void VipsValueSetArrayDouble(global::System.IntPtr value, double[] array, int n);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_value_get_array_int")]
            internal static extern int* VipsValueGetArrayInt(global::System.IntPtr value, int* n);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_value_set_array_int")]
            internal static extern void VipsValueSetArrayInt(global::System.IntPtr value, int[] array, int n);
        }

        public static string VipsValueGetRefString(global::NetVips.AutoGen.GValue value, ref ulong length)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            fixed (ulong* __refParamPtr1 = &length)
            {
                var __arg1 = __refParamPtr1;
                var __ret = __Internal.VipsValueGetRefString(__arg0, __arg1);
                return Marshal.PtrToStringAnsi(__ret);
            }
        }

        public static void VipsValueSetRefString(global::NetVips.AutoGen.GValue value, string str)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            __Internal.VipsValueSetRefString(__arg0, str);
        }

        public static global::System.IntPtr VipsValueGetBlob(global::NetVips.AutoGen.GValue value, ref ulong length)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            fixed (ulong* __refParamPtr1 = &length)
            {
                var __arg1 = __refParamPtr1;
                var __ret = __Internal.VipsValueGetBlob(__arg0, __arg1);
                return __ret;
            }
        }

        public static void VipsValueSetBlob(global::NetVips.AutoGen.GValue value, global::NetVips.AutoGen.VipsCallbackFn free_fn, global::System.IntPtr data, ulong length)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            var __arg1 = free_fn == null ? global::System.IntPtr.Zero : Marshal.GetFunctionPointerForDelegate(free_fn);
            __Internal.VipsValueSetBlob(__arg0, __arg1, data, length);
        }

        public static void VipsValueSetBlobFree(global::NetVips.AutoGen.GValue value, global::System.IntPtr data, ulong length)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            __Internal.VipsValueSetBlobFree(__arg0, data, length);
        }

        public static double* VipsValueGetArrayDouble(global::NetVips.AutoGen.GValue value, ref int n)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            fixed (int* __refParamPtr1 = &n)
            {
                var __arg1 = __refParamPtr1;
                var __ret = __Internal.VipsValueGetArrayDouble(__arg0, __arg1);
                return __ret;
            }
        }

        public static void VipsValueSetArrayDouble(global::NetVips.AutoGen.GValue value, double[] array, int n)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            __Internal.VipsValueSetArrayDouble(__arg0, array, n);
        }

        public static int* VipsValueGetArrayInt(global::NetVips.AutoGen.GValue value, ref int n)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            fixed (int* __refParamPtr1 = &n)
            {
                var __arg1 = __refParamPtr1;
                var __ret = __Internal.VipsValueGetArrayInt(__arg0, __arg1);
                return __ret;
            }
        }

        public static void VipsValueSetArrayInt(global::NetVips.AutoGen.GValue value, int[] array, int n)
        {
            var __arg0 = ReferenceEquals(value, null) ? global::System.IntPtr.Zero : value.__Instance;
            __Internal.VipsValueSetArrayInt(__arg0, array, n);
        }
    }
}
