// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace NetVips.AutoGen
{
    public unsafe partial class util
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_enum_nick")]
            internal static extern global::System.IntPtr VipsEnumNick(ulong enm, int value);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_enum_from_nick")]
            internal static extern int VipsEnumFromNick([MarshalAs(UnmanagedType.LPStr)] string domain, ulong type, [MarshalAs(UnmanagedType.LPStr)] string str);
        }

        public static string VipsEnumNick(ulong enm, int value)
        {
            var __ret = __Internal.VipsEnumNick(enm, value);
            return Marshal.PtrToStringAnsi(__ret);
        }

        public static int VipsEnumFromNick(string domain, ulong type, string str)
        {
            var __ret = __Internal.VipsEnumFromNick(domain, type, str);
            return __ret;
        }
    }
}
