// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace NetVips.AutoGen
{
    public unsafe partial class vips
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_init")]
            internal static extern int VipsInit([MarshalAs(UnmanagedType.LPStr)] string argv0);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_leak_set")]
            internal static extern void VipsLeakSet(int leak);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("libvips-42.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="vips_version")]
            internal static extern int VipsVersion(int flag);
        }

        public static int VipsInit(string argv0)
        {
            var __ret = __Internal.VipsInit(argv0);
            return __ret;
        }

        public static void VipsLeakSet(int leak)
        {
            __Internal.VipsLeakSet(leak);
        }

        public static int VipsVersion(int flag)
        {
            var __ret = __Internal.VipsVersion(flag);
            return __ret;
        }
    }
}
