name: CI
on: [ push, pull_request ]
permissions: {}
jobs:
  CI:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            container: mcr.microsoft.com/dotnet/sdk:9.0-bookworm-slim
            script: ./build.sh
          - os: ubuntu-24.04-arm
            container: mcr.microsoft.com/dotnet/sdk:9.0-bookworm-slim-arm64v8
            script: ./build.sh
          - os: ubuntu-24.04
            container: rockylinux:8
            script: ./build.sh
          - os: ubuntu-24.04
            container: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.20
            script: ./build.sh
          # https://github.com/orgs/community/discussions/53407
          #- os: ubuntu-24.04-arm
          #  container: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.20-arm64v8
          #  script: ./build.sh
          - os: macos-13
            script: ./build.sh
          - os: windows-2022
            script: .\build.ps1
          - os: windows-11-arm
            script: .\build.ps1
    steps:
      - name: Dependencies (Debian 12)
        if: contains(matrix.container, 'bookworm')
        run: |
          apt-get update
          apt-get install -y fontconfig-config
      - name: Dependencies (Rocky Linux 8)
        if: contains(matrix.container, 'rockylinux')
        run: dnf install -y dotnet-sdk-9.0 google-noto-sans-fonts which
      - name: Dependencies (Alpine 3.20)
        if: contains(matrix.container, 'alpine')
        run: apk add bash font-noto --update-cache
      - name: Setup dotnet
        if: ${{ matrix.container == '' }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: ${{ matrix.script }}
