name: CI
on: [ push, pull_request ]
permissions: {}
jobs:
  CI:
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}
      volumes:
        - ${{ contains(matrix.container, 'alpine3.20-arm64v8') && '/opt:/opt:rw,rshared' || ' ' }}
        - ${{ contains(matrix.container, 'alpine3.20-arm64v8') && '/opt:/__e/node24:ro,rshared' || ' ' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            container: mcr.microsoft.com/dotnet/sdk:9.0-bookworm-slim
            script: ./build.sh
          - os: ubuntu-24.04-arm
            container: mcr.microsoft.com/dotnet/sdk:9.0-bookworm-slim-arm64v8
            script: ./build.sh
          - os: ubuntu-24.04
            container: rockylinux:8
            script: ./build.sh
          - os: ubuntu-24.04
            container: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.20
            script: ./build.sh
          - os: ubuntu-24.04-arm
            container: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.20-arm64v8
            script: ./build.sh
          - os: macos-13
            script: ./build.sh
          - os: windows-2022
            script: .\build.ps1
          - os: windows-11-arm
            script: .\build.ps1
    steps:
      - name: Allow Linux musl containers on ARM64 runners # https://github.com/actions/runner/issues/801#issuecomment-2394425757
        if: contains(matrix.container, 'alpine3.20-arm64v8')
        run: |
          sed -i "/^ID=/s/alpine/NotpineForGHA/" /etc/os-release
          apk add nodejs --update-cache
          mkdir /opt/bin
          ln -s /usr/bin/node /opt/bin/node
      - name: Dependencies (Debian 12)
        if: contains(matrix.container, 'bookworm')
        run: |
          apt-get update
          apt-get install -y fontconfig-config
      - name: Dependencies (Rocky Linux 8)
        if: contains(matrix.container, 'rockylinux')
        run: dnf install -y dotnet-sdk-9.0 google-noto-sans-fonts which
      - name: Dependencies (Alpine 3.20)
        if: contains(matrix.container, 'alpine')
        run: apk add bash font-noto --update-cache
      - name: Setup dotnet
        if: matrix.container == ''
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test
        run: ${{ matrix.script }}
